default_platform(:android)

platform :android do
  desc "Build debug APK"
  lane :debug do
    sh "cd .. && flutter build apk --debug"
  end

  desc "Build release APK"
  lane :release_apk do
    sh "cd .. && flutter build apk --release"
  end

  desc "Build release App Bundle"
  lane :release_bundle do
    sh "cd .. && flutter build appbundle --release"
  end

  desc "Deploy to Google Play internal track"
  lane :deploy do
    release_bundle
    upload_to_play_store(
      track: "internal",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end

platform :ios do
  desc "Build release IPA"
  lane :release do
    sh "cd .. && flutter build ios --release"
    build_ios_app(
      workspace: "ios/Runner.xcworkspace",
      scheme: "Runner",
      export_options_plist: "ios/ExportOptions.plist",
    )
  end

  desc "Deploy to TestFlight"
  lane :beta do
    release
    upload_to_testflight(
      skip_waiting_for_build_processing: true,
    )
  end
end
