/// Uzbekistan administrative regions and their districts for delivery address selection.
abstract final class UzbekistanRegions {
  /// All region names
  static const List<String> regions = [
    'Toshkent shahri',
    'Toshkent viloyati',
    'Samarqand viloyati',
    'Buxoro viloyati',
    "Farg'ona viloyati",
    'Andijon viloyati',
    'Namangan viloyati',
    'Qashqadaryo viloyati',
    'Surxondaryo viloyati',
    'Jizzax viloyati',
    'Sirdaryo viloyati',
    'Navoiy viloyati',
    'Xorazm viloyati',
    "Qoraqalpog'iston Respublikasi",
  ];

  /// Districts/areas mapped by region name
  static const Map<String, List<String>> areasByRegion = {
    'Toshkent shahri': [
      'Bektemir',
      'Chilonzor',
      'Mirobod',
      "Mirzo Ulug'bek",
      'Olmazor',
      'Sergeli',
      'Shayxontohur',
      'Uchtepa',
      'Yakkasaroy',
      'Yashnobod',
      'Yunusobod',
    ],
    'Toshkent viloyati': [
      'Angren',
      'Bekobod',
      'Chirchiq',
      'Olmaliq',
      "Bo'ka tumani",
      "Bo'stonliq tumani",
      'Chinoz tumani',
      "Qibray tumani",
      "Ohangaron tumani",
      "Zangiota tumani",
      "Yuqorichirchiq tumani",
      "Parkent tumani",
    ],
    'Samarqand viloyati': [
      'Samarqand shahri',
      'Bulung\'ur tumani',
      'Ishtixon tumani',
      'Jomboy tumani',
      'Kattaqo\'rg\'on tumani',
      'Narpay tumani',
      'Pastdarg\'om tumani',
      'Payariq tumani',
      'Urgut tumani',
    ],
    'Buxoro viloyati': [
      'Buxoro shahri',
      'Kogon shahri',
      "G'ijduvon tumani",
      'Jondor tumani',
      'Kogon tumani',
      'Olot tumani',
      'Peshku tumani',
      'Romitan tumani',
      'Shofirkon tumani',
      'Vobkent tumani',
    ],
    "Farg'ona viloyati": [
      "Farg'ona shahri",
      "Qo'qon shahri",
      'Marg\'ilon shahri',
      'Quvasoy shahri',
      'Beshariq tumani',
      "Bog'dod tumani",
      'Dang\'ara tumani',
      "Farg'ona tumani",
      'Furqat tumani',
      'Rishton tumani',
      "So'x tumani",
      "Yozyovon tumani",
    ],
    'Andijon viloyati': [
      'Andijon shahri',
      'Xonobod shahri',
      'Asaka tumani',
      'Baliqchi tumani',
      "Bo'z tumani",
      'Buloqboshi tumani',
      'Izboskan tumani',
      'Jalolquduq tumani',
      'Marhamat tumani',
      'Oltinko\'l tumani',
      'Paxtaobod tumani',
      'Shahrixon tumani',
    ],
    'Namangan viloyati': [
      'Namangan shahri',
      'Chortoq tumani',
      'Chust tumani',
      'Kosonsoy tumani',
      'Mingbuloq tumani',
      'Namangan tumani',
      'Norin tumani',
      'Pop tumani',
      "To'raqo'rg'on tumani",
      'Uchqo\'rg\'on tumani',
      'Yangiqo\'rg\'on tumani',
    ],
    'Qashqadaryo viloyati': [
      'Qarshi shahri',
      'Shahrisabz shahri',
      'Dehqonobod tumani',
      "G'uzor tumani",
      'Kasbi tumani',
      'Kitob tumani',
      'Koson tumani',
      'Mirishkor tumani',
      'Muborak tumani',
      'Nishon tumani',
      'Chiroqchi tumani',
      'Yakkabog\' tumani',
    ],
    'Surxondaryo viloyati': [
      'Termiz shahri',
      'Angor tumani',
      'Boysun tumani',
      'Denov tumani',
      'Jarqo\'rg\'on tumani',
      'Muzrabot tumani',
      'Oltinsoy tumani',
      'Qiziriq tumani',
      'Sariosiyo tumani',
      'Sherobod tumani',
      'Sho\'rchi tumani',
      "Uzun tumani",
    ],
    'Jizzax viloyati': [
      'Jizzax shahri',
      'Arnasoy tumani',
      "Baxmal tumani",
      "Do'stlik tumani",
      "Forish tumani",
      "G'allaorol tumani",
      'Mirzacho\'l tumani',
      'Paxtakor tumani',
      'Yangiobod tumani',
      'Zomin tumani',
      'Zarbdor tumani',
    ],
    'Sirdaryo viloyati': [
      'Guliston shahri',
      'Shirin shahri',
      'Yangiyer shahri',
      'Boyovut tumani',
      'Guliston tumani',
      'Mirzaobod tumani',
      'Oqoltin tumani',
      'Sardoba tumani',
      'Sayxunobod tumani',
      'Xovos tumani',
    ],
    'Navoiy viloyati': [
      'Navoiy shahri',
      'Zarafshon shahri',
      'Konimex tumani',
      'Karmana tumani',
      'Navbahor tumani',
      'Nurota tumani',
      'Tomdi tumani',
      'Uchquduq tumani',
      'Xatirchi tumani',
    ],
    'Xorazm viloyati': [
      'Urganch shahri',
      'Xiva shahri',
      'Bogot tumani',
      'Gurlan tumani',
      'Xonqa tumani',
      'Hazorasp tumani',
      'Qo\'shko\'pir tumani',
      'Shovot tumani',
      'Urganch tumani',
      'Yangiariq tumani',
      'Yangibozor tumani',
    ],
    "Qoraqalpog'iston Respublikasi": [
      'Nukus shahri',
      "Amudaryo tumani",
      "Beruniy tumani",
      "Chimboy tumani",
      "Ellikqal'a tumani",
      "Kegeyli tumani",
      "Mo'ynoq tumani",
      "Nukus tumani",
      "Qanliko'l tumani",
      "Qo'ng'irot tumani",
      "Shumanay tumani",
      "Taxtako'pir tumani",
      "To'rtko'l tumani",
      "Xo'jayli tumani",
    ],
  };
}
